version: "3"
services:
  api:
    image: suhelkhanca/social-app
    ports:
      - 80:8000
    env_file:
        - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=social_app
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
